# Generated by Django 3.1.3 on 2025-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('nombre', models.TextField(blank=True)),
                ('raza', models.TextField(blank=True)),
                ('peso', models.TextField(blank=True)),
            ],
        ),
    ]
