# Generated by Django 3.1.3 on 2025-06-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerdos', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='Cerdos',
            new_name='cerdos',
        ),
    ]
